name: pickly_design_system
description: "Pickly 디자인 시스템 패키지"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true