/// Benefit Program Model (v8.0)
///
/// Represents a program type/category for benefit announcements.
/// Replaces the old "announcement_types" concept with "programs".
/// Used in benefit screens to filter announcements by program type.
///
/// Example: "청년", "신혼부부", "고령자" for housing category
library;

import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

part 'benefit_program.g.dart';

/// BenefitProgram - Temporarily using B-Lite pattern (Equatable + json_serializable)
/// due to Freezed 3.2.3 mixin generation bug.
///
/// Migration to Freezed when fixed:
/// 1. Update Freezed to >=3.3.0 (when bug is patched)
/// 2. Replace with: @freezed class BenefitProgram with _$BenefitProgram { ... }
/// 3. Add back: part 'benefit_program.freezed.dart';
/// 4. Remove Equatable and manual implementations
@JsonSerializable()
class BenefitProgram extends Equatable {
  final String id;
  final String benefitCategoryId;
  final String title;
  final String? description;
  final String? iconUrl;
  final int sortOrder;
  final bool isActive;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const BenefitProgram({
    required this.id,
    required this.benefitCategoryId,
    required this.title,
    this.description,
    this.iconUrl,
    this.sortOrder = 0,
    this.isActive = true,
    this.createdAt,
    this.updatedAt,
  });

  /// JSON deserialization (auto-generated by json_serializable)
  factory BenefitProgram.fromJson(Map<String, dynamic> json) =>
      _$BenefitProgramFromJson(json);

  /// JSON serialization (auto-generated by json_serializable)
  Map<String, dynamic> toJson() => _$BenefitProgramToJson(this);

  /// copyWith - Manual implementation for immutability
  BenefitProgram copyWith({
    String? id,
    String? benefitCategoryId,
    String? title,
    String? description,
    String? iconUrl,
    int? sortOrder,
    bool? isActive,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return BenefitProgram(
      id: id ?? this.id,
      benefitCategoryId: benefitCategoryId ?? this.benefitCategoryId,
      title: title ?? this.title,
      description: description ?? this.description,
      iconUrl: iconUrl ?? this.iconUrl,
      sortOrder: sortOrder ?? this.sortOrder,
      isActive: isActive ?? this.isActive,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  /// Equality props (auto-handled by Equatable)
  @override
  List<Object?> get props => [
        id,
        benefitCategoryId,
        title,
        description,
        iconUrl,
        sortOrder,
        isActive,
        createdAt,
        updatedAt,
      ];

  /// toString (auto-handled by Equatable)
  @override
  bool get stringify => true;
}
