import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

part 'announcement_file.g.dart';

/// AnnouncementFile - Temporarily using B-Lite pattern (Equatable + json_serializable)
/// due to Freezed 3.2.3 mixin generation bug.
///
/// Migration to Freezed when fixed:
/// 1. Update Freezed to >=3.3.0 (when bug is patched)
/// 2. Replace with: @freezed class AnnouncementFile with _$AnnouncementFile { ... }
/// 3. Add back: part 'announcement_file.freezed.dart';
/// 4. Remove Equatable and manual implementations
@JsonSerializable()
class AnnouncementFile extends Equatable {
  final String id;
  final String announcementId;
  final String fileName;
  final String fileUrl;
  final String? fileType;
  final int? fileSize;
  final String? description;
  final DateTime createdAt;
  final DateTime? updatedAt;
  final int displayOrder;
  final Map<String, dynamic> customData;

  const AnnouncementFile({
    required this.id,
    required this.announcementId,
    required this.fileName,
    required this.fileUrl,
    this.fileType,
    this.fileSize,
    this.description,
    required this.createdAt,
    this.updatedAt,
    this.displayOrder = 0,
    this.customData = const {},
  });

  /// JSON deserialization (auto-generated by json_serializable)
  factory AnnouncementFile.fromJson(Map<String, dynamic> json) =>
      _$AnnouncementFileFromJson(json);

  /// JSON serialization (auto-generated by json_serializable)
  Map<String, dynamic> toJson() => _$AnnouncementFileToJson(this);

  /// copyWith - Manual implementation for immutability
  AnnouncementFile copyWith({
    String? id,
    String? announcementId,
    String? fileName,
    String? fileUrl,
    String? fileType,
    int? fileSize,
    String? description,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? displayOrder,
    Map<String, dynamic>? customData,
  }) {
    return AnnouncementFile(
      id: id ?? this.id,
      announcementId: announcementId ?? this.announcementId,
      fileName: fileName ?? this.fileName,
      fileUrl: fileUrl ?? this.fileUrl,
      fileType: fileType ?? this.fileType,
      fileSize: fileSize ?? this.fileSize,
      description: description ?? this.description,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      displayOrder: displayOrder ?? this.displayOrder,
      customData: customData ?? this.customData,
    );
  }

  /// Equality props (auto-handled by Equatable)
  @override
  List<Object?> get props => [
        id,
        announcementId,
        fileName,
        fileUrl,
        fileType,
        fileSize,
        description,
        createdAt,
        updatedAt,
        displayOrder,
        customData,
      ];

  /// toString (auto-handled by Equatable)
  @override
  bool get stringify => true;

  // ==================== Custom Helper Methods ====================
  // These methods are preserved from the original Freezed implementation

  /// Get custom field by key with type safety
  T? getCustomField<T>(String key) => customData[key] as T?;

  /// Format file size for display
  String get fileSizeFormatted {
    if (fileSize == null) return 'Unknown size';
    final kb = fileSize! / 1024;
    if (kb < 1024) {
      return '${kb.toStringAsFixed(1)} KB';
    }
    final mb = kb / 1024;
    return '${mb.toStringAsFixed(1)} MB';
  }

  /// Check if file is PDF
  bool get isPdf =>
      fileType?.toLowerCase() == 'pdf' ||
      fileName.toLowerCase().endsWith('.pdf');

  /// Check if file is an image
  bool get isImage => ['jpg', 'jpeg', 'png', 'gif', 'webp']
      .any((ext) => fileName.toLowerCase().endsWith('.$ext'));

  /// Check if file is a document (Office files)
  bool get isDocument => ['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx']
      .any((ext) => fileName.toLowerCase().endsWith('.$ext'));
}
