import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

part 'benefit_category.g.dart';

/// BenefitCategory - Temporarily using B-Lite pattern (Equatable + json_serializable)
/// due to Freezed 3.2.3 mixin generation bug.
///
/// Migration to Freezed when fixed:
/// 1. Update Freezed to >=3.3.0 (when bug is patched)
/// 2. Replace with: @freezed class BenefitCategory with _$BenefitCategory { ... }
/// 3. Add back: part 'benefit_category.freezed.dart';
/// 4. Remove Equatable and manual implementations
@JsonSerializable()
class BenefitCategory extends Equatable {
  final String id;

  /// Category title (maps to 'title' column in database)
  final String title;

  final String slug;
  final String? description;

  @JsonKey(name: 'icon_url')
  final String? iconUrl;

  @JsonKey(name: 'banner_image_url')
  final String? bannerImageUrl;

  @JsonKey(name: 'banner_link_url')
  final String? bannerLinkUrl;

  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @JsonKey(name: 'updated_at')
  final DateTime? updatedAt;

  @JsonKey(name: 'is_active')
  final bool isActive;

  /// Sort order (maps to 'sort_order' column in database)
  @JsonKey(name: 'sort_order')
  final int sortOrder;

  const BenefitCategory({
    required this.id,
    required this.title,
    required this.slug,
    this.description,
    this.iconUrl,
    this.bannerImageUrl,
    this.bannerLinkUrl,
    required this.createdAt,
    this.updatedAt,
    this.isActive = true,
    this.sortOrder = 0,
  });

  /// JSON deserialization (auto-generated by json_serializable)
  factory BenefitCategory.fromJson(Map<String, dynamic> json) =>
      _$BenefitCategoryFromJson(json);

  /// JSON serialization (auto-generated by json_serializable)
  Map<String, dynamic> toJson() => _$BenefitCategoryToJson(this);

  /// copyWith - Manual implementation for immutability
  BenefitCategory copyWith({
    String? id,
    String? title,
    String? slug,
    String? description,
    String? iconUrl,
    String? bannerImageUrl,
    String? bannerLinkUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? isActive,
    int? sortOrder,
  }) {
    return BenefitCategory(
      id: id ?? this.id,
      title: title ?? this.title,
      slug: slug ?? this.slug,
      description: description ?? this.description,
      iconUrl: iconUrl ?? this.iconUrl,
      bannerImageUrl: bannerImageUrl ?? this.bannerImageUrl,
      bannerLinkUrl: bannerLinkUrl ?? this.bannerLinkUrl,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isActive: isActive ?? this.isActive,
      sortOrder: sortOrder ?? this.sortOrder,
    );
  }

  /// Equality props (auto-handled by Equatable)
  @override
  List<Object?> get props => [
        id,
        title,
        slug,
        description,
        iconUrl,
        bannerImageUrl,
        bannerLinkUrl,
        createdAt,
        updatedAt,
        isActive,
        sortOrder,
      ];

  /// toString (auto-handled by Equatable)
  @override
  bool get stringify => true;
}
