// Mocks generated by Mockito 5.4.4 from annotations
// in pickly_mobile/test/features/onboarding/age_category_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pickly_mobile/models/age_category.dart' as _i5;
import 'package:pickly_mobile/repositories/age_category_repository.dart' as _i3;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRealtimeChannel_0 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AgeCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgeCategoryRepository extends _i1.Mock
    implements _i3.AgeCategoryRepository {
  MockAgeCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.AgeCategory>> fetchActiveCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchActiveCategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.AgeCategory>>.value(<_i5.AgeCategory>[]),
      ) as _i4.Future<List<_i5.AgeCategory>>);

  @override
  _i4.Future<_i5.AgeCategory?> fetchCategoryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCategoryById,
          [id],
        ),
        returnValue: _i4.Future<_i5.AgeCategory?>.value(),
      ) as _i4.Future<_i5.AgeCategory?>);

  @override
  _i2.RealtimeChannel subscribeToCategories({
    void Function(_i5.AgeCategory)? onInsert,
    void Function(_i5.AgeCategory)? onUpdate,
    void Function(String)? onDelete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToCategories,
          [],
          {
            #onInsert: onInsert,
            #onUpdate: onUpdate,
            #onDelete: onDelete,
          },
        ),
        returnValue: _FakeRealtimeChannel_0(
          this,
          Invocation.method(
            #subscribeToCategories,
            [],
            {
              #onInsert: onInsert,
              #onUpdate: onUpdate,
              #onDelete: onDelete,
            },
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  _i4.Future<bool> validateCategoryIds(List<String>? categoryIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateCategoryIds,
          [categoryIds],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
