import '../models/policy.dart';

/// Mock policy data for development and testing
///
/// This will be replaced with:
/// - Supabase backend data (admin-managed)
/// - Public API integration
class MockPolicyData {
  /// Housing category policies
  static final List<Policy> housingPolicies = [
    const Policy(
      id: 'housing_001',
      title: '화성동탄2 A93 동탄호수공원 행복주택',
      organization: '장기전세주택(GH)',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/12',
      isRecruiting: true,
      categoryId: 'housing',
      description: '동탄호수공원 인근 행복주택 입주자 모집',
      deadline: '2025/05/15',
      targetAudience: '무주택 청년, 신혼부부',
    ),
    const Policy(
      id: 'housing_002',
      title: '서울시 청년 매입임대주택 입주자 모집',
      organization: 'SH공사',
      imageUrl: 'assets/images/test/house_banner_test_01.png',
      postedDate: '2025/04/10',
      isRecruiting: true,
      categoryId: 'housing',
      description: '서울시 청년을 위한 매입임대주택',
      deadline: '2025/05/20',
      targetAudience: '만 19~39세 청년',
    ),
    const Policy(
      id: 'housing_003',
      title: '경기도 공공임대주택 신청 안내',
      organization: '경기주택도시공사(GH)',
      imageUrl: 'assets/images/test/house_banner_test_02.png',
      postedDate: '2025/04/05',
      isRecruiting: false,
      categoryId: 'housing',
      description: '경기도 내 공공임대주택 입주 신청',
      deadline: '2025/04/30',
      targetAudience: '무주택 세대주',
    ),
    const Policy(
      id: 'housing_004',
      title: '신혼희망타운 사전예약 접수',
      organization: 'LH한국토지주택공사',
      imageUrl: 'assets/images/test/house_banner_test_03.png',
      postedDate: '2025/03/28',
      isRecruiting: true,
      categoryId: 'housing',
      description: '신혼부부를 위한 분양형 공공주택',
      deadline: '2025/06/01',
      targetAudience: '혼인 7년 이내 신혼부부',
    ),
    const Policy(
      id: 'housing_005',
      title: '행복주택 3차 입주자 모집 공고',
      organization: 'LH한국토지주택공사',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/20',
      isRecruiting: false,
      categoryId: 'housing',
      description: '대학생, 청년, 신혼부부를 위한 행복주택',
      deadline: '2025/04/15',
      targetAudience: '대학생, 청년, 신혼부부',
    ),
    const Policy(
      id: 'housing_006',
      title: '인천 청라지구 공공분양 입주자 모집',
      organization: 'LH한국토지주택공사',
      imageUrl: 'assets/images/test/house_banner_test_01.png',
      postedDate: '2025/03/15',
      isRecruiting: true,
      categoryId: 'housing',
      description: '청라국제도시 공공분양주택 입주 모집',
      deadline: '2025/05/10',
      targetAudience: '무주택 세대주',
    ),
    const Policy(
      id: 'housing_007',
      title: '부산 에코델타시티 스마트시티 분양',
      organization: '부산도시공사',
      imageUrl: 'assets/images/test/house_banner_test_02.png',
      postedDate: '2025/03/10',
      isRecruiting: true,
      categoryId: 'housing',
      description: '친환경 스마트시티 공공주택',
      deadline: '2025/06/15',
      targetAudience: '일반 분양 희망자',
    ),
    const Policy(
      id: 'housing_008',
      title: '전월세 보증금 반환 보증 신청',
      organization: '주택도시보증공사',
      imageUrl: 'assets/images/test/house_banner_test_03.png',
      postedDate: '2025/03/05',
      isRecruiting: true,
      categoryId: 'housing',
      description: '전월세 보증금 안전하게 보호',
      deadline: '2025/12/31',
      targetAudience: '전월세 계약자',
    ),
    const Policy(
      id: 'housing_009',
      title: '청년 전세자금 대출 지원',
      organization: '주택금융공사',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/02/28',
      isRecruiting: false,
      categoryId: 'housing',
      description: '저금리 청년 전세자금 대출',
      deadline: '2025/03/31',
      targetAudience: '만 19~34세 청년',
    ),
    const Policy(
      id: 'housing_010',
      title: '다자녀 가구 특별공급 신청',
      organization: 'LH한국토지주택공사',
      imageUrl: 'assets/images/test/house_banner_test_01.png',
      postedDate: '2025/02/20',
      isRecruiting: true,
      categoryId: 'housing',
      description: '다자녀 가구 우선 공급 주택',
      deadline: '2025/07/31',
      targetAudience: '3자녀 이상 가구',
    ),
  ];

  /// Education category policies
  static final List<Policy> educationPolicies = [
    const Policy(
      id: 'education_001',
      title: '국가장학금 2학기 신청 안내',
      organization: '한국장학재단',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/15',
      isRecruiting: true,
      categoryId: 'education',
      description: '대학생을 위한 국가장학금 지원',
      deadline: '2025/05/31',
      targetAudience: '대학 재학생',
    ),
    const Policy(
      id: 'education_002',
      title: '서울시 청년 교육비 지원 사업',
      organization: '서울시청',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/12',
      isRecruiting: true,
      categoryId: 'education',
      description: '청년 자기계발을 위한 교육비 지원',
      deadline: '2025/06/15',
      targetAudience: '만 19~34세 서울시 거주 청년',
    ),
    const Policy(
      id: 'education_003',
      title: '취업 연계 직업훈련 과정 모집',
      organization: '고용노동부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/08',
      isRecruiting: false,
      categoryId: 'education',
      description: '취업을 위한 무료 직업훈련',
      deadline: '2025/04/20',
      targetAudience: '구직자',
    ),
    const Policy(
      id: 'education_004',
      title: '경기도 청년 학자금 대출 이자 지원',
      organization: '경기도청',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/01',
      isRecruiting: true,
      categoryId: 'education',
      description: '학자금 대출 이자 감면 지원',
      deadline: '2025/12/31',
      targetAudience: '경기도 거주 청년',
    ),
    const Policy(
      id: 'education_005',
      title: '고등학생 교육비 지원 사업',
      organization: '교육부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/25',
      isRecruiting: true,
      categoryId: 'education',
      description: '저소득층 고등학생 교육비 지원',
      deadline: '2025/07/31',
      targetAudience: '저소득층 고등학생',
    ),
    const Policy(
      id: 'education_006',
      title: 'K-디지털 트레이닝 교육 과정',
      organization: '과학기술정보통신부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/20',
      isRecruiting: true,
      categoryId: 'education',
      description: 'AI, 빅데이터 등 디지털 역량 교육',
      deadline: '2025/05/31',
      targetAudience: '청년 구직자',
    ),
    const Policy(
      id: 'education_007',
      title: '외국어 교육비 지원 프로그램',
      organization: '서울시교육청',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/15',
      isRecruiting: false,
      categoryId: 'education',
      description: '청소년 외국어 교육 지원',
      deadline: '2025/04/10',
      targetAudience: '중고등학생',
    ),
    const Policy(
      id: 'education_008',
      title: '평생교육 바우처 지원 사업',
      organization: '교육부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/10',
      isRecruiting: true,
      categoryId: 'education',
      description: '성인 평생교육 수강료 지원',
      deadline: '2025/08/31',
      targetAudience: '성인 학습자',
    ),
    const Policy(
      id: 'education_009',
      title: '대학생 해외 연수 지원 프로그램',
      organization: '한국연구재단',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/05',
      isRecruiting: true,
      categoryId: 'education',
      description: '우수 대학생 해외 연수 기회 제공',
      deadline: '2025/06/30',
      targetAudience: '대학 재학생',
    ),
    const Policy(
      id: 'education_010',
      title: '자격증 취득 비용 지원',
      organization: '고용노동부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/02/28',
      isRecruiting: true,
      categoryId: 'education',
      description: '취업 관련 자격증 취득 비용 환급',
      deadline: '2025/12/31',
      targetAudience: '미취업 청년',
    ),
  ];

  /// Support category policies
  static final List<Policy> supportPolicies = [
    const Policy(
      id: 'support_001',
      title: '청년 구직활동 지원금 신청',
      organization: '고용노동부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/18',
      isRecruiting: true,
      categoryId: 'support',
      description: '구직활동 중인 청년에게 월 50만원 지원',
      deadline: '2025/05/31',
      targetAudience: '만 18~34세 미취업 청년',
    ),
    const Policy(
      id: 'support_002',
      title: '청년 창업 지원 사업',
      organization: '중소벤처기업부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/15',
      isRecruiting: true,
      categoryId: 'support',
      description: '청년 창업자를 위한 자금 및 멘토링 지원',
      deadline: '2025/06/30',
      targetAudience: '만 39세 이하 예비창업자',
    ),
    const Policy(
      id: 'support_003',
      title: '면접 정장 대여 서비스',
      organization: '서울시청',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/10',
      isRecruiting: true,
      categoryId: 'support',
      description: '취업 준비생을 위한 정장 무료 대여',
      deadline: '2025/12/31',
      targetAudience: '서울시 거주 구직자',
    ),
    const Policy(
      id: 'support_004',
      title: '청년 내일채움공제 가입 안내',
      organization: '고용노동부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/05',
      isRecruiting: false,
      categoryId: 'support',
      description: '중소기업 청년 근로자 자산형성 지원',
      deadline: '2025/04/20',
      targetAudience: '중소기업 청년 근로자',
    ),
    const Policy(
      id: 'support_005',
      title: '일자리 안정 자금 지원',
      organization: '고용노동부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/30',
      isRecruiting: true,
      categoryId: 'support',
      description: '영세사업주 인건비 지원',
      deadline: '2025/12/31',
      targetAudience: '30인 미만 사업주',
    ),
    const Policy(
      id: 'support_006',
      title: '청년 저축계좌 지원 사업',
      organization: '보건복지부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/25',
      isRecruiting: true,
      categoryId: 'support',
      description: '근로청년 자산형성 지원',
      deadline: '2025/06/30',
      targetAudience: '저소득 근로 청년',
    ),
    const Policy(
      id: 'support_007',
      title: '중소기업 청년 취업 지원금',
      organization: '중소벤처기업부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/20',
      isRecruiting: false,
      categoryId: 'support',
      description: '중소기업 취업 청년 인센티브',
      deadline: '2025/04/15',
      targetAudience: '중소기업 신입사원',
    ),
    const Policy(
      id: 'support_008',
      title: '청년 월세 지원 사업',
      organization: '국토교통부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/15',
      isRecruiting: true,
      categoryId: 'support',
      description: '청년 월세 최대 20만원 지원',
      deadline: '2025/11/30',
      targetAudience: '만 19~34세 청년',
    ),
    const Policy(
      id: 'support_009',
      title: '장애인 고용장려금 신청',
      organization: '한국장애인고용공단',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/10',
      isRecruiting: true,
      categoryId: 'support',
      description: '장애인 고용 사업주 장려금',
      deadline: '2025/12/31',
      targetAudience: '장애인 고용 사업체',
    ),
    const Policy(
      id: 'support_010',
      title: '경력단절여성 재취업 지원',
      organization: '여성가족부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/05',
      isRecruiting: true,
      categoryId: 'support',
      description: '경력단절여성 직업교육 및 취업 지원',
      deadline: '2025/09/30',
      targetAudience: '경력단절 여성',
    ),
  ];

  /// Transportation category policies
  static final List<Policy> transportationPolicies = [
    const Policy(
      id: 'transportation_001',
      title: '청년 교통비 지원 사업',
      organization: '서울시청',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/20',
      isRecruiting: true,
      categoryId: 'transportation',
      description: '청년 대중교통 이용 요금 지원',
      deadline: '2025/06/30',
      targetAudience: '만 19~34세 서울시 거주 청년',
    ),
    const Policy(
      id: 'transportation_002',
      title: '경기도 K-패스 카드 신청',
      organization: '경기도청',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/15',
      isRecruiting: true,
      categoryId: 'transportation',
      description: '대중교통 무제한 이용권',
      deadline: '2025/12/31',
      targetAudience: '경기도민',
    ),
    const Policy(
      id: 'transportation_003',
      title: '장애인 콜택시 이용권 지원',
      organization: '보건복지부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/10',
      isRecruiting: true,
      categoryId: 'transportation',
      description: '장애인을 위한 특별교통수단 지원',
      deadline: '2025/12/31',
      targetAudience: '등록 장애인',
    ),
    const Policy(
      id: 'transportation_004',
      title: '저소득층 유류비 지원',
      organization: '산업통상자원부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/04/05',
      isRecruiting: false,
      categoryId: 'transportation',
      description: '저소득층 가구 유류비 보조',
      deadline: '2025/04/25',
      targetAudience: '기초생활수급자',
    ),
    const Policy(
      id: 'transportation_005',
      title: '전기차 구매 보조금 신청',
      organization: '환경부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/28',
      isRecruiting: true,
      categoryId: 'transportation',
      description: '친환경 전기차 구매 시 최대 700만원 지원',
      deadline: '2025/11/30',
      targetAudience: '전기차 구매 희망자',
    ),
    const Policy(
      id: 'transportation_006',
      title: '수도권 통합환승 할인제 확대',
      organization: '국토교통부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/22',
      isRecruiting: true,
      categoryId: 'transportation',
      description: '대중교통 환승 할인 혜택 확대',
      deadline: '2025/12/31',
      targetAudience: '대중교통 이용자',
    ),
    const Policy(
      id: 'transportation_007',
      title: '자전거 출퇴근 마일리지 제도',
      organization: '서울시청',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/18',
      isRecruiting: false,
      categoryId: 'transportation',
      description: '자전거 출퇴근 시 인센티브 지급',
      deadline: '2025/04/05',
      targetAudience: '서울시 직장인',
    ),
    const Policy(
      id: 'transportation_008',
      title: '수소차 구매 지원금 신청',
      organization: '환경부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/12',
      isRecruiting: true,
      categoryId: 'transportation',
      description: '수소 전기차 구매 보조금 지원',
      deadline: '2025/10/31',
      targetAudience: '수소차 구매 희망자',
    ),
    const Policy(
      id: 'transportation_009',
      title: '고령자 교통비 지원 사업',
      organization: '보건복지부',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/08',
      isRecruiting: true,
      categoryId: 'transportation',
      description: '65세 이상 어르신 교통비 지원',
      deadline: '2025/12/31',
      targetAudience: '만 65세 이상 어르신',
    ),
    const Policy(
      id: 'transportation_010',
      title: '지하철 무료 와이파이 확대',
      organization: '서울교통공사',
      imageUrl: 'assets/images/test/list_sample.png',
      postedDate: '2025/03/01',
      isRecruiting: true,
      categoryId: 'transportation',
      description: '지하철 역사 및 열차 내 무료 와이파이',
      deadline: '2025/12/31',
      targetAudience: '지하철 이용객',
    ),
  ];

  /// Get policies by category ID
  static List<Policy> getPoliciesByCategory(String categoryId) {
    switch (categoryId) {
      case 'housing':
        return housingPolicies;
      case 'education':
        return educationPolicies;
      case 'support':
        return supportPolicies;
      case 'transportation':
        return transportationPolicies;
      default:
        return [];
    }
  }

  /// Get all policies
  static List<Policy> getAllPolicies() {
    return [
      ...housingPolicies,
      ...educationPolicies,
      ...supportPolicies,
      ...transportationPolicies,
    ];
  }
}
